//! Supported Node and Bunode option table.

#[derive(Clone, Copy)]
pub(super) struct OptionSpec {
  pub(super) long: &'static [&'static str],
  pub(super) short: Option<char>,
  pub(super) value: ValueMode,
  pub(super) node_options_allowed: bool,
  pub(super) action: OptionAction,
}

#[derive(Clone, Copy, PartialEq, Eq)]
pub(super) enum ValueMode {
  None,
  Required,
  OptionalEquals,
}

#[derive(Clone, Copy)]
pub(super) enum OptionAction {
  Help,
  Version,
  Eval,
  Print,
  ForwardFlag(&'static str),
  ForwardValue(&'static str),
  ForwardOptionalValue(&'static str),
}

pub(super) const OPTION_SPECS: &[OptionSpec] = &[
  OptionSpec {
    long: &["--help"],
    short: Some('h'),
    value: ValueMode::None,
    node_options_allowed: false,
    action: OptionAction::Help,
  },
  OptionSpec {
    long: &["--version"],
    short: Some('v'),
    value: ValueMode::None,
    node_options_allowed: false,
    action: OptionAction::Version,
  },
  OptionSpec {
    long: &["--eval"],
    short: Some('e'),
    value: ValueMode::Required,
    node_options_allowed: false,
    action: OptionAction::Eval,
  },
  OptionSpec {
    long: &["--print"],
    short: Some('p'),
    value: ValueMode::Required,
    node_options_allowed: false,
    action: OptionAction::Print,
  },
  OptionSpec {
    long: &["--require"],
    short: Some('r'),
    value: ValueMode::Required,
    node_options_allowed: true,
    action: OptionAction::ForwardValue("--preload"),
  },
  OptionSpec {
    long: &["--import"],
    short: None,
    value: ValueMode::Required,
    node_options_allowed: true,
    action: OptionAction::ForwardValue("--preload"),
  },
  OptionSpec {
    long: &["--inspect"],
    short: None,
    value: ValueMode::OptionalEquals,
    node_options_allowed: true,
    action: OptionAction::ForwardOptionalValue("--inspect"),
  },
  OptionSpec {
    long: &["--inspect-brk"],
    short: None,
    value: ValueMode::OptionalEquals,
    node_options_allowed: true,
    action: OptionAction::ForwardOptionalValue("--inspect-brk"),
  },
  OptionSpec {
    long: &["--inspect-wait"],
    short: None,
    value: ValueMode::OptionalEquals,
    node_options_allowed: true,
    action: OptionAction::ForwardOptionalValue("--inspect-wait"),
  },
  OptionSpec {
    long: &["--conditions"],
    short: Some('C'),
    value: ValueMode::Required,
    node_options_allowed: true,
    action: OptionAction::ForwardValue("--conditions"),
  },
  OptionSpec {
    long: &["--cpu-prof"],
    short: None,
    value: ValueMode::None,
    node_options_allowed: true,
    action: OptionAction::ForwardFlag("--cpu-prof"),
  },
  OptionSpec {
    long: &["--cpu-prof-dir"],
    short: None,
    value: ValueMode::Required,
    node_options_allowed: true,
    action: OptionAction::ForwardValue("--cpu-prof-dir"),
  },
  OptionSpec {
    long: &["--cpu-prof-interval"],
    short: None,
    value: ValueMode::Required,
    node_options_allowed: true,
    action: OptionAction::ForwardValue("--cpu-prof-interval"),
  },
  OptionSpec {
    long: &["--cpu-prof-name"],
    short: None,
    value: ValueMode::Required,
    node_options_allowed: true,
    action: OptionAction::ForwardValue("--cpu-prof-name"),
  },
  OptionSpec {
    long: &["--heap-prof"],
    short: None,
    value: ValueMode::None,
    node_options_allowed: true,
    action: OptionAction::ForwardFlag("--heap-prof"),
  },
  OptionSpec {
    long: &["--heap-prof-dir"],
    short: None,
    value: ValueMode::Required,
    node_options_allowed: true,
    action: OptionAction::ForwardValue("--heap-prof-dir"),
  },
  OptionSpec {
    long: &["--heap-prof-name"],
    short: None,
    value: ValueMode::Required,
    node_options_allowed: true,
    action: OptionAction::ForwardValue("--heap-prof-name"),
  },
  OptionSpec {
    long: &["--dns-result-order"],
    short: None,
    value: ValueMode::Required,
    node_options_allowed: true,
    action: OptionAction::ForwardValue("--dns-result-order"),
  },
  OptionSpec {
    long: &["--env-file"],
    short: None,
    value: ValueMode::Required,
    node_options_allowed: true,
    action: OptionAction::ForwardValue("--env-file"),
  },
  OptionSpec {
    long: &["--expose-gc"],
    short: None,
    value: ValueMode::None,
    node_options_allowed: true,
    action: OptionAction::ForwardFlag("--expose-gc"),
  },
  OptionSpec {
    long: &["--no-addons"],
    short: None,
    value: ValueMode::None,
    node_options_allowed: true,
    action: OptionAction::ForwardFlag("--no-addons"),
  },
  OptionSpec {
    long: &["--no-deprecation"],
    short: None,
    value: ValueMode::None,
    node_options_allowed: true,
    action: OptionAction::ForwardFlag("--no-deprecation"),
  },
  OptionSpec {
    long: &["--throw-deprecation"],
    short: None,
    value: ValueMode::None,
    node_options_allowed: true,
    action: OptionAction::ForwardFlag("--throw-deprecation"),
  },
  OptionSpec {
    long: &["--title"],
    short: None,
    value: ValueMode::Required,
    node_options_allowed: true,
    action: OptionAction::ForwardValue("--title"),
  },
  OptionSpec {
    long: &["--unhandled-rejections"],
    short: None,
    value: ValueMode::Required,
    node_options_allowed: true,
    action: OptionAction::ForwardValue("--unhandled-rejections"),
  },
  OptionSpec {
    long: &["--use-bundled-ca"],
    short: None,
    value: ValueMode::None,
    node_options_allowed: true,
    action: OptionAction::ForwardFlag("--use-bundled-ca"),
  },
  OptionSpec {
    long: &["--use-openssl-ca"],
    short: None,
    value: ValueMode::None,
    node_options_allowed: true,
    action: OptionAction::ForwardFlag("--use-openssl-ca"),
  },
  OptionSpec {
    long: &["--use-system-ca"],
    short: None,
    value: ValueMode::None,
    node_options_allowed: true,
    action: OptionAction::ForwardFlag("--use-system-ca"),
  },
  OptionSpec {
    long: &["--zero-fill-buffers"],
    short: None,
    value: ValueMode::None,
    node_options_allowed: true,
    action: OptionAction::ForwardFlag("--zero-fill-buffers"),
  },
  OptionSpec {
    long: &["--bun-config"],
    short: None,
    value: ValueMode::Required,
    node_options_allowed: false,
    action: OptionAction::ForwardValue("--config"),
  },
  OptionSpec {
    long: &["--bun-console-depth"],
    short: None,
    value: ValueMode::Required,
    node_options_allowed: false,
    action: OptionAction::ForwardValue("--console-depth"),
  },
  OptionSpec {
    long: &["--bun-env-file"],
    short: None,
    value: ValueMode::Required,
    node_options_allowed: false,
    action: OptionAction::ForwardValue("--env-file"),
  },
  OptionSpec {
    long: &["--bun-fetch-preconnect"],
    short: None,
    value: ValueMode::Required,
    node_options_allowed: false,
    action: OptionAction::ForwardValue("--fetch-preconnect"),
  },
  OptionSpec {
    long: &["--bun-hot"],
    short: None,
    value: ValueMode::None,
    node_options_allowed: false,
    action: OptionAction::ForwardFlag("--hot"),
  },
  OptionSpec {
    long: &["--bun-install"],
    short: None,
    value: ValueMode::Required,
    node_options_allowed: false,
    action: OptionAction::ForwardValue("--install"),
  },
  OptionSpec {
    long: &["--bun-no-clear-screen"],
    short: None,
    value: ValueMode::None,
    node_options_allowed: false,
    action: OptionAction::ForwardFlag("--no-clear-screen"),
  },
  OptionSpec {
    long: &["--bun-no-env-file"],
    short: None,
    value: ValueMode::None,
    node_options_allowed: false,
    action: OptionAction::ForwardFlag("--no-env-file"),
  },
  OptionSpec {
    long: &["--bun-port"],
    short: None,
    value: ValueMode::Required,
    node_options_allowed: false,
    action: OptionAction::ForwardValue("--port"),
  },
  OptionSpec {
    long: &["--bun-prefer-latest"],
    short: None,
    value: ValueMode::None,
    node_options_allowed: false,
    action: OptionAction::ForwardFlag("--prefer-latest"),
  },
  OptionSpec {
    long: &["--bun-prefer-offline"],
    short: None,
    value: ValueMode::None,
    node_options_allowed: false,
    action: OptionAction::ForwardFlag("--prefer-offline"),
  },
  OptionSpec {
    long: &["--bun-preload"],
    short: None,
    value: ValueMode::Required,
    node_options_allowed: false,
    action: OptionAction::ForwardValue("--preload"),
  },
  OptionSpec {
    long: &["--bun-smol"],
    short: None,
    value: ValueMode::None,
    node_options_allowed: false,
    action: OptionAction::ForwardFlag("--smol"),
  },
  OptionSpec {
    long: &["--bun-user-agent"],
    short: None,
    value: ValueMode::Required,
    node_options_allowed: false,
    action: OptionAction::ForwardValue("--user-agent"),
  },
  OptionSpec {
    long: &["--bun-watch"],
    short: None,
    value: ValueMode::None,
    node_options_allowed: false,
    action: OptionAction::ForwardFlag("--watch"),
  },
];
