//! Supported Node and Bunode option table.

use semver::Version;

#[derive(Clone, Copy)]
pub struct OptionShape {
  specs: &'static [OptionSpec],
}

#[derive(Clone, Copy)]
pub(super) struct OptionSpec {
  pub(super) long: &'static [&'static str],
  pub(super) short: Option<char>,
  pub(super) value: ValueMode,
  pub(super) node_options_allowed: bool,
  pub(super) exec_argv: bool,
  pub(super) help: Option<OptionHelp>,
}

#[derive(Clone, Copy, PartialEq, Eq)]
pub(super) enum ValueMode {
  None,
  Required,
  OptionalEquals,
}

#[derive(Clone, Copy, PartialEq, Eq)]
pub(super) enum HelpSection {
  Node,
  Bun,
}

#[derive(Clone, Copy)]
pub(super) struct OptionHelp {
  pub(super) section: HelpSection,
  pub(super) row: HelpRow,
}

#[derive(Clone, Copy)]
pub(super) struct HelpRow {
  pub(super) left: &'static str,
  pub(super) description: &'static str,
}

pub const fn option_shape_for_bun(_version: &Version) -> OptionShape {
  option_shape_for_bun_baseline()
}

const fn option_shape_for_bun_baseline() -> OptionShape {
  OptionShape { specs: OPTION_SPECS }
}

impl OptionShape {
  pub(super) const fn specs(&self) -> &'static [OptionSpec] {
    self.specs
  }
}

macro_rules! option_spec {
  ($source:ident, [$($long:literal),+], $short:expr, $value:expr, $left:literal, $description:expr $(,)?) => {
    OptionSpec {
      long: &[$($long),+],
      short: $short,
      value: $value,
      node_options_allowed: option_spec!(@node_options_allowed $source),
      exec_argv: option_spec!(@exec_argv $source),
      help: Some(OptionHelp {
        section: option_spec!(@help_section $source),
        row: HelpRow { left: $left, description: $description },
      }),
    }
  };
  (@node_options_allowed command) => { false };
  (@node_options_allowed node_cli) => { false };
  (@node_options_allowed node) => { true };
  (@node_options_allowed bun) => { false };
  (@exec_argv command) => { true };
  (@exec_argv node_cli) => { true };
  (@exec_argv node) => { true };
  (@exec_argv bun) => { false };
  (@help_section command) => { HelpSection::Node };
  (@help_section node_cli) => { HelpSection::Node };
  (@help_section node) => { HelpSection::Node };
  (@help_section bun) => { HelpSection::Bun };
}

pub(super) const OPTION_SPECS: &[OptionSpec] = &[
  option_spec!(
    command,
    ["--help"],
    Some('h'),
    ValueMode::None,
    "-h, --help",
    "print node command line options (currently set)",
  ),
  option_spec!(
    command,
    ["--version"],
    Some('v'),
    ValueMode::None,
    "-v, --version",
    "print Node.js version",
  ),
  option_spec!(
    command,
    ["--eval"],
    Some('e'),
    ValueMode::Required,
    "-e, --eval=...",
    "evaluate script",
  ),
  option_spec!(
    command,
    ["--print"],
    Some('p'),
    ValueMode::Required,
    "-p, --print [...]",
    "evaluate script and print result",
  ),
  option_spec!(
    node,
    ["--require"],
    Some('r'),
    ValueMode::Required,
    "-r, --require=...",
    "CommonJS module to preload (option can be repeated)",
  ),
  option_spec!(
    node,
    ["--import"],
    None,
    ValueMode::Required,
    "--import=...",
    "ES module to preload (option can be repeated)",
  ),
  OptionSpec {
    long: &["--experimental-import-meta-resolve"],
    short: None,
    value: ValueMode::None,
    node_options_allowed: true,
    exec_argv: true,
    help: None,
  },
  OptionSpec {
    long: &["--disable-warning"],
    short: None,
    value: ValueMode::Required,
    node_options_allowed: true,
    exec_argv: true,
    help: None,
  },
  option_spec!(
    node,
    ["--inspect"],
    None,
    ValueMode::OptionalEquals,
    "--inspect[=[host:]port]",
    "activate inspector on host:port (default: 127.0.0.1:9229)",
  ),
  option_spec!(
    node,
    ["--inspect-brk"],
    None,
    ValueMode::OptionalEquals,
    "--inspect-brk[=[host:]port]",
    "activate inspector on host:port and break at start of user script",
  ),
  option_spec!(
    node,
    ["--inspect-wait"],
    None,
    ValueMode::OptionalEquals,
    "--inspect-wait[=[host:]port]",
    "activate inspector on host:port and wait for debugger to be attached",
  ),
  option_spec!(
    node,
    ["--conditions"],
    Some('C'),
    ValueMode::Required,
    "-C, --conditions=...",
    "additional user conditions for conditional exports and imports",
  ),
  option_spec!(
    node,
    ["--cpu-prof"],
    None,
    ValueMode::None,
    "--cpu-prof",
    concat!(
      "Start the V8 CPU profiler on start up, and write the CPU profile to disk before exit. ",
      "If --cpu-prof-dir is not specified, write the profile to the current working directory.",
    ),
  ),
  option_spec!(
    node,
    ["--cpu-prof-dir"],
    None,
    ValueMode::Required,
    "--cpu-prof-dir=...",
    concat!(
      "Directory where the V8 profiles generated by --cpu-prof will be placed. ",
      "Does not affect --prof.",
    ),
  ),
  option_spec!(
    node,
    ["--cpu-prof-interval"],
    None,
    ValueMode::Required,
    "--cpu-prof-interval=...",
    concat!(
      "specified sampling interval in microseconds for the V8 CPU profile generated ",
      "with --cpu-prof. (default: 1000)",
    ),
  ),
  option_spec!(
    node,
    ["--cpu-prof-name"],
    None,
    ValueMode::Required,
    "--cpu-prof-name=...",
    "specified file name of the V8 CPU profile generated with --cpu-prof",
  ),
  option_spec!(
    node,
    ["--heap-prof"],
    None,
    ValueMode::None,
    "--heap-prof",
    concat!(
      "Start the V8 heap profiler on start up, and write the heap profile to disk before exit. ",
      "If --heap-prof-dir is not specified, write the profile to the current working directory.",
    ),
  ),
  option_spec!(
    node,
    ["--heap-prof-dir"],
    None,
    ValueMode::Required,
    "--heap-prof-dir=...",
    "Directory where the V8 heap profiles generated by --heap-prof will be placed.",
  ),
  option_spec!(
    node,
    ["--heap-prof-name"],
    None,
    ValueMode::Required,
    "--heap-prof-name=...",
    "specified file name of the V8 heap profile generated with --heap-prof",
  ),
  option_spec!(
    node,
    ["--dns-result-order"],
    None,
    ValueMode::Required,
    "--dns-result-order=...",
    concat!(
      "set default value of verbatim in dns.lookup. Options are 'ipv4first' ",
      "(IPv4 addresses are placed before IPv6 addresses) 'ipv6first' ",
      "(IPv6 addresses are placed before IPv4 addresses) 'verbatim' ",
      "(addresses are in the order the DNS resolver returned)",
    ),
  ),
  option_spec!(
    node_cli,
    ["--env-file"],
    None,
    ValueMode::Required,
    "--env-file=...",
    "set environment variables from supplied file",
  ),
  option_spec!(node, ["--expose-gc"], None, ValueMode::None, "--expose-gc", "expose gc extension",),
  option_spec!(
    node,
    ["--no-addons"],
    None,
    ValueMode::None,
    "--no-addons",
    "disable loading native addons",
  ),
  option_spec!(
    node,
    ["--no-deprecation"],
    None,
    ValueMode::None,
    "--no-deprecation",
    "silence deprecation warnings",
  ),
  option_spec!(
    node,
    ["--throw-deprecation"],
    None,
    ValueMode::None,
    "--throw-deprecation",
    "throw an exception on deprecations",
  ),
  option_spec!(
    node,
    ["--title"],
    None,
    ValueMode::Required,
    "--title=...",
    "the process title to use on startup",
  ),
  option_spec!(
    node,
    ["--unhandled-rejections"],
    None,
    ValueMode::Required,
    "--unhandled-rejections=...",
    concat!(
      "define unhandled rejections behavior. Options are 'strict' (always raise an error), ",
      "'throw' (raise an error unless 'unhandledRejection' hook is set), 'warn' (log a warning), ",
      "'none' (silence warnings), 'warn-with-error-code' (log a warning and set exit code 1 unless ",
      "'unhandledRejection' hook is set). (default: throw)",
    ),
  ),
  option_spec!(
    node,
    ["--use-bundled-ca"],
    None,
    ValueMode::None,
    "--use-bundled-ca",
    "use bundled CA store",
  ),
  option_spec!(
    node,
    ["--use-openssl-ca"],
    None,
    ValueMode::None,
    "--use-openssl-ca",
    "use OpenSSL's default CA store (default)",
  ),
  option_spec!(
    node,
    ["--use-system-ca"],
    None,
    ValueMode::None,
    "--use-system-ca",
    "use system's CA store",
  ),
  option_spec!(
    node,
    ["--zero-fill-buffers"],
    None,
    ValueMode::None,
    "--zero-fill-buffers",
    "automatically zero-fill all newly allocated Buffer instances",
  ),
  option_spec!(
    bun,
    ["--bun-config"],
    None,
    ValueMode::Required,
    "--bun-config=<val>",
    "Specify path to Bun config file. Default $cwd/bunfig.toml",
  ),
  option_spec!(
    bun,
    ["--bun-console-depth"],
    None,
    ValueMode::Required,
    "--bun-console-depth=<val>",
    "Set the default depth for console.log object inspection (default: 2)",
  ),
  option_spec!(
    bun,
    ["--bun-env-file"],
    None,
    ValueMode::Required,
    "--bun-env-file=<val>",
    "Load environment variables from the specified file(s)",
  ),
  option_spec!(
    bun,
    ["--bun-fetch-preconnect"],
    None,
    ValueMode::Required,
    "--bun-fetch-preconnect=<val>",
    "Preconnect to a URL while code is loading",
  ),
  option_spec!(
    bun,
    ["--bun-hot"],
    None,
    ValueMode::None,
    "--bun-hot",
    "Enable auto reload in the Bun runtime, test runner, or bundler",
  ),
  option_spec!(
    bun,
    ["--bun-install"],
    None,
    ValueMode::Required,
    "--bun-install=<val>",
    concat!(
      "Configure auto-install behavior. One of \"auto\" (default, auto-installs when no node_modules), ",
      "\"fallback\" (missing packages only), \"force\" (always).",
    ),
  ),
  option_spec!(
    bun,
    ["--bun-no-clear-screen"],
    None,
    ValueMode::None,
    "--bun-no-clear-screen",
    "Disable clearing the terminal screen on reload when --hot or --watch is enabled",
  ),
  option_spec!(
    bun,
    ["--bun-no-env-file"],
    None,
    ValueMode::None,
    "--bun-no-env-file",
    "Disable automatic loading of .env files",
  ),
  option_spec!(
    bun,
    ["--bun-port"],
    None,
    ValueMode::Required,
    "--bun-port=<val>",
    "Set the default port for Bun.serve",
  ),
  option_spec!(
    bun,
    ["--bun-prefer-latest"],
    None,
    ValueMode::None,
    "--bun-prefer-latest",
    "Use the latest matching versions of packages in the Bun runtime, always checking npm",
  ),
  option_spec!(
    bun,
    ["--bun-prefer-offline"],
    None,
    ValueMode::None,
    "--bun-prefer-offline",
    "Skip staleness checks for packages in the Bun runtime and resolve from disk",
  ),
  option_spec!(
    bun,
    ["--bun-preload"],
    None,
    ValueMode::Required,
    "--bun-preload=<val>",
    "Import a module before other modules are loaded",
  ),
  option_spec!(
    bun,
    ["--bun-smol"],
    None,
    ValueMode::None,
    "--bun-smol",
    "Use less memory, but run garbage collection more often",
  ),
  option_spec!(
    bun,
    ["--bun-user-agent"],
    None,
    ValueMode::Required,
    "--bun-user-agent=<val>",
    "Set the default User-Agent header for HTTP requests",
  ),
  option_spec!(
    bun,
    ["--bun-watch"],
    None,
    ValueMode::None,
    "--bun-watch",
    "Automatically restart the process on file change",
  ),
];

pub(super) fn find_long_option(shape: &OptionShape, name: &str) -> Option<&'static OptionSpec> {
  shape.specs.iter().find(|spec| spec.long.contains(&name))
}

pub(super) fn find_short_option(shape: &OptionShape, short: char) -> Option<&'static OptionSpec> {
  shape.specs.iter().find(|spec| spec.short == Some(short))
}

#[cfg(test)]
mod tests {
  use std::collections::HashSet;

  #[test]
  fn option_specs_should_have_unique_names() {
    let shape = super::option_shape_for_bun_baseline();
    let mut long_names = HashSet::new();
    let mut short_names = HashSet::new();

    for spec in shape.specs() {
      for long in spec.long {
        assert!(long.starts_with("--"));
        assert!(long_names.insert(*long), "duplicate long option {long}");
      }

      if let Some(short) = spec.short {
        assert!(short_names.insert(short), "duplicate short option -{short}");
      }
    }
  }
}
